export const START_DISCOVERY = 'START_DISCOVERY';
export const STOP_DISCOVERY = 'STOP_DISCOVERY';
export const DISCOVERY_DONE = 'DISCOVERY_DONE';
export const DISCOVERY_FAILURE = 'DISCOVERY_FAILURE';

export const START_CONNECT = 'START_CONNECT';
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS';
export const CONNECT_FAILURE = 'CONNECT_FAILURE';
export const DISCONNECT = 'DISCONNECT';
export const START_MEASURE = 'START_MEASURE';
export const STOP_MEASURE = 'STOP_MEASURE';
export const MEASURE_DONE = 'MEASURE_DONE';
